\c postgres;
DROP DATABASE IF EXISTS route;
CREATE DATABASE route;
\c route;

DROP TABLE IF EXISTS probleme_historiques CASCADE;
DROP TABLE IF EXISTS signalement_historiques CASCADE;
DROP TABLE IF EXISTS utilisateur_statuts CASCADE;
DROP TABLE IF EXISTS problemes CASCADE;
DROP TABLE IF EXISTS signalements CASCADE;
DROP TABLE IF EXISTS points CASCADE;
DROP TABLE IF EXISTS utilisateurs CASCADE;
DROP TABLE IF EXISTS villes CASCADE;
DROP TABLE IF EXISTS entreprises CASCADE;
DROP TABLE IF EXISTS probleme_statuts CASCADE;
DROP TABLE IF EXISTS signalement_statuts CASCADE;
DROP TABLE IF EXISTS statuts CASCADE;
DROP TABLE IF EXISTS profils CASCADE;

